name: CI to Docker hub

on:
  push:
    branches: [master]
    tags:
      - v*
env:
  IMAGE_NAME: yamllint
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose-test.yml ]; then
            docker-compose --file docker-compose-test.yml build
            docker-compose --file docker-compose-test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build yamllint
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login docker.io -u ${{ secrets.DOCKER_ID }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=wpninfra/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == master ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION